# Generated by Django 3.2.5 on 2021-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_user_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
