# Generated by Django 3.2.5 on 2021-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/images/integration/'),
        ),
        migrations.AddField(
            model_name='integration',
            name='redirct',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
