# Generated by Django 3.2.5 on 2021-09-01 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0002_integration_integrationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.integration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IntegrationDetails',
        ),
    ]
