# Generated by Django 3.2.5 on 2021-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_rename_redirct_integration_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationkey',
            name='calendar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationkey',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
