# Generated by Django 3.2.5 on 2021-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20210904_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationkey',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
