# Generated by Django 3.2.5 on 2021-09-16 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0005_integrationkey_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='authorization_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='key_secret',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='integrationkey',
            name='acceses_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrationkey',
            name='last_token_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='integrationkey',
            name='meta_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationkey',
            name='public_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrationkey',
            name='token_refresh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integrationkey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
