# Generated by Django 3.2.5 on 2021-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
