# Generated by Django 3.2.5 on 2021-08-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_speciality_staff_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
