# Generated by Django 3.2.5 on 2021-08-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_tenantsettingsmodel_tenantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant'),
        ),
    ]
