# Generated by Django 3.2.5 on 2021-10-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_booking_meeting_link'),
        ('tenants', '0006_auto_20211013_2250'),
    ]

    operations = [
    ]
