# Generated by Django 3.2.5 on 2021-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenantsettings_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/images/tenants/'),
        ),
    ]
