# Generated by Django 3.2.5 on 2021-08-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenantsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.tenant'),
        ),
    ]
