# Generated by Django 3.2.5 on 2021-10-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_merge_20211014_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
