# Generated by Django 3.2.5 on 2021-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
