# Generated by Django 3.2.5 on 2021-10-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('tenants', '0007_alter_staff_doctors'),
        ('tenants', '0009_booking_event_id'),
    ]

    operations = [
    ]
