# Generated by Django 3.2.5 on 2021-08-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_auto_20210830_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.booking'),
        ),
    ]
