# Generated by Django 3.2.5 on 2021-10-18 22:04

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_email'),
        ('tenants', '0009_booking_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
