# Generated by Django 3.2.5 on 2021-08-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_bookingdetail_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.booking'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='brief_description',
            field=models.TextField(max_length=100),
        ),
    ]
