# Generated by Django 3.2.5 on 2021-10-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_bookingdetail_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tenant',
        ),
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tenants.tenant'),
        ),
    ]
