# Generated by Django 3.2.5 on 2021-08-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_auto_20210831_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletimeframe',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_frames', to='tenants.schedule'),
        ),
    ]
