# Generated by Django 3.2.5 on 2021-10-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_auto_20211019_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('booking_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_detail', to='tenants.bookingdetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDoctorDetailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booking_attachments/')),
                ('booking_doctor_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_doctor', to='tenants.bookingdoctordetail')),
            ],
        ),
    ]
