# Generated by Django 3.2.5 on 2021-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_bookingdoctordetail_bookingdoctordetailfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
