# Generated by Django 3.2.5 on 2021-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_bookingdetail_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
