# Generated by Django 3.2.5 on 2021-07-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='core/static/images/avatar/default.jpg', upload_to='core/static/images/avatar/'),
        ),
    ]
