# Generated by Django 3.2.5 on 2021-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allegiance_detail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_alcohol',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_allegiance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_disability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_smoker',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
