# Generated by Django 3.2.5 on 2021-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='booking_attachments/'),
        ),
    ]
