# Generated by Django 3.2.5 on 2021-08-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('position', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Specialty for default true, is necesary for use', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Specialty for doctor is default true, necesary for use', verbose_name='active')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='specialties.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
