# Generated by Django 3.2.5 on 2021-07-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
