# Generated by Django 3.2.5 on 2021-08-14 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialties', through='specialties.Staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
