# Generated by Django 3.2.5 on 2021-08-14 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='specialties', to=settings.AUTH_USER_MODEL),
        ),
    ]
