# Generated by Django 3.2.5 on 2021-08-14 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0002_auto_20210814_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
