# Generated by Django 3.2.5 on 2021-07-21 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0002_alter_specialty_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Specialty for doctor is default true, necesary for use', verbose_name='active')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='specialties.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
