# Generated by Django 3.2.6 on 2021-08-23 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkOut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='precio',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.CharField(max_length=3),
            preserve_default=True,
        ),
    ]
