# Generated by Django 3.2.6 on 2021-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkOut', '0002_auto_20210823_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.CharField(max_length=3),
        ),
    ]
