# Generated by Django 3.2.6 on 2021-08-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkOut', '0003_alter_item_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
