# Generated by Django 3.2.6 on 2021-08-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkOut', '0004_remove_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
